// packages/state/src/core/Solid/types.ts
import type { StoreApi } from '@ilokesto/store';
import type { Accessor } from 'solid-js';

import type { ReducerAction } from '../../types/ReduceFn.js';
import type { ReadonlySnapshot } from '../shared/readonlySnapshot.js';

export type Selector<T, S> = (state: ReadonlySnapshot<T>) => S;
export type SetStateAction<T> = Parameters<StoreApi<T>['setState']>[0];
export type StateWriter<T> = (nextState: SetStateAction<T>) => void;
export type ActionWriter<Action> = (action: Action) => void;

export type SolidStateResult<S, T> = Readonly<{
  state: Accessor<S>;
  setState: StateWriter<T>;
}>;

export type SolidReducerResult<S, Action> = Readonly<{
  state: Accessor<S>;
  dispatch: ActionWriter<Action>;
}>;

export type UseState<T> = {
  (): SolidStateResult<ReadonlySnapshot<T>, T>;
  <S>(selector: Selector<T, S>): SolidStateResult<S, T>;
  writeOnly: () => StateWriter<T>;
  readOnly: {
    (): ReadonlySnapshot<T>;
    <S>(selector: Selector<T, S>): S;
  };
};

export type UseReducer<T, Action extends ReducerAction> = {
  (): SolidReducerResult<ReadonlySnapshot<T>, Action>;
  <S>(selector: Selector<T, S>): SolidReducerResult<S, Action>;
  writeOnly: () => ActionWriter<Action>;
  readOnly: {
    (): ReadonlySnapshot<T>;
    <S>(selector: Selector<T, S>): S;
  };
};

// packages/state/src/core/Angular/types.ts
import type { StoreApi } from '@ilokesto/store';
import type { DestroyRef, Signal } from '@angular/core';

import type { ReducerAction } from '../../types/ReduceFn.js';
import type { ReadonlySnapshot } from '../shared/readonlySnapshot.js';

export type Selector<T, S> = (state: ReadonlySnapshot<T>) => S;
export type SetStateAction<T> = Parameters<StoreApi<T>['setState']>[0];
export type StateWriter<T> = (nextState: SetStateAction<T>) => void;
export type ActionWriter<Action> = (action: Action) => void;
export type AngularOptions = {
  destroyRef?: DestroyRef;
};

export type AngularStateResult<S, T> = Readonly<{
  state: Signal<S>;
  setState: StateWriter<T>;
  subscribe: StoreApi<T>['subscribe'];
}>;

export type AngularReducerResult<S, T, Action> = Readonly<{
  state: Signal<S>;
  dispatch: ActionWriter<Action>;
  subscribe: StoreApi<T>['subscribe'];
}>;

export type UseState<T> = {
  (): AngularStateResult<ReadonlySnapshot<T>, T>;
  (options: AngularOptions): AngularStateResult<ReadonlySnapshot<T>, T>;
  <S>(selector: Selector<T, S>, options?: AngularOptions): AngularStateResult<S, T>;
  writeOnly: () => StateWriter<T>;
  readOnly: {
    (): ReadonlySnapshot<T>;
    <S>(selector: Selector<T, S>): S;
  };
  subscribe: StoreApi<T>['subscribe'];
};

export type UseReducer<T, Action extends ReducerAction> = {
  (): AngularReducerResult<ReadonlySnapshot<T>, T, Action>;
  (options: AngularOptions): AngularReducerResult<ReadonlySnapshot<T>, T, Action>;
  <S>(selector: Selector<T, S>, options?: AngularOptions): AngularReducerResult<S, T, Action>;
  writeOnly: () => ActionWriter<Action>;
  readOnly: {
    (): ReadonlySnapshot<T>;
    <S>(selector: Selector<T, S>): S;
  };
  subscribe: StoreApi<T>['subscribe'];
};
