// packages/form/src/solid/useFormSnapshot.ts
import { createSignal, onCleanup, type Accessor } from 'solid-js';
import type { Form, FormState } from '../core/index';

/** core form snapshot을 Solid signal로 연결한다. */
export function useFormSnapshot<TValues>(form: Form<TValues>): Accessor<Readonly<FormState<TValues>>> {
  const [snapshot, setSnapshot] = createSignal<Readonly<FormState<TValues>>>(form.getState(), { equals: false });
  const unsubscribe = form.subscribe(() => {
    setSnapshot(form.getState());
  });

  onCleanup(unsubscribe);

  return snapshot;
}

// packages/form/src/react/useFormSnapshot.ts
import { useSyncExternalStore } from 'react';
import type { Form, FormState } from '../core/index';

/** React 18+ 외부 store 구독 API로 core form snapshot을 구독한다. */
export function useFormSnapshot<TValues>(form: Form<TValues>): Readonly<FormState<TValues>> {
  return useSyncExternalStore(
    listener => form.subscribe(listener),
    () => form.getState(),
    () => form.getState(),
  );
}
